NIFTY50_TICKERS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "BHARTIARTL.NS", "ICICIBANK.NS",
    "INFOSYS.NS", "SBIN.NS", "HINDUNILVR.NS", "ITC.NS", "LT.NS",
    "KOTAKBANK.NS", "AXISBANK.NS", "BAJFINANCE.NS", "ASIANPAINT.NS", "MARUTI.NS",
    "TITAN.NS", "SUNPHARMA.NS", "ULTRACEMCO.NS", "NESTLEIND.NS", "WIPRO.NS",
    "ONGC.NS", "NTPC.NS", "POWERGRID.NS", "M&M.NS", "TATAMOTORS.NS",
    "HCLTECH.NS", "BAJAJFINSV.NS", "TATASTEEL.NS", "ADANIENT.NS", "ADANIPORTS.NS",
    "COALINDIA.NS", "DIVISLAB.NS", "DRREDDY.NS", "EICHERMOT.NS", "GRASIM.NS",
    "HEROMOTOCO.NS", "HINDALCO.NS", "INDUSINDBK.NS", "JSWSTEEL.NS", "CIPLA.NS",
    "BAJAJ-AUTO.NS", "APOLLOHOSP.NS", "BPCL.NS", "BRITANNIA.NS", "SHRIRAMFIN.NS",
    "SBILIFE.NS", "HDFCLIFE.NS", "TECHM.NS", "TATACONSUM.NS", "LTIM.NS",
]

TICKER_TO_NAME = {
    "RELIANCE.NS": "Reliance Industries",
    "TCS.NS": "Tata Consultancy Services",
    "HDFCBANK.NS": "HDFC Bank",
    "BHARTIARTL.NS": "Bharti Airtel",
    "ICICIBANK.NS": "ICICI Bank",
    "INFOSYS.NS": "Infosys",
    "SBIN.NS": "State Bank of India",
    "HINDUNILVR.NS": "Hindustan Unilever",
    "ITC.NS": "ITC Limited",
    "LT.NS": "Larsen & Toubro",
    "KOTAKBANK.NS": "Kotak Mahindra Bank",
    "AXISBANK.NS": "Axis Bank",
    "BAJFINANCE.NS": "Bajaj Finance",
    "ASIANPAINT.NS": "Asian Paints",
    "MARUTI.NS": "Maruti Suzuki",
    "TITAN.NS": "Titan Company",
    "SUNPHARMA.NS": "Sun Pharmaceutical",
    "ULTRACEMCO.NS": "UltraTech Cement",
    "NESTLEIND.NS": "Nestle India",
    "WIPRO.NS": "Wipro",
    "ONGC.NS": "Oil & Natural Gas Corp",
    "NTPC.NS": "NTPC Limited",
    "POWERGRID.NS": "Power Grid Corp",
    "M&M.NS": "Mahindra & Mahindra",
    "TATAMOTORS.NS": "Tata Motors",
    "HCLTECH.NS": "HCL Technologies",
    "BAJAJFINSV.NS": "Bajaj Finserv",
    "TATASTEEL.NS": "Tata Steel",
    "ADANIENT.NS": "Adani Enterprises",
    "ADANIPORTS.NS": "Adani Ports",
    "COALINDIA.NS": "Coal India",
    "DIVISLAB.NS": "Divi's Laboratories",
    "DRREDDY.NS": "Dr. Reddy's Laboratories",
    "EICHERMOT.NS": "Eicher Motors",
    "GRASIM.NS": "Grasim Industries",
    "HEROMOTOCO.NS": "Hero MotoCorp",
    "HINDALCO.NS": "Hindalco Industries",
    "INDUSINDBK.NS": "IndusInd Bank",
    "JSWSTEEL.NS": "JSW Steel",
    "CIPLA.NS": "Cipla",
    "BAJAJ-AUTO.NS": "Bajaj Auto",
    "APOLLOHOSP.NS": "Apollo Hospitals",
    "BPCL.NS": "Bharat Petroleum",
    "BRITANNIA.NS": "Britannia Industries",
    "SHRIRAMFIN.NS": "Shriram Finance",
    "SBILIFE.NS": "SBI Life Insurance",
    "HDFCLIFE.NS": "HDFC Life Insurance",
    "TECHM.NS": "Tech Mahindra",
    "TATACONSUM.NS": "Tata Consumer Products",
    "LTIM.NS": "LTIMindtree",
}

# Short name → ticker mapping for news extraction
NAME_TO_TICKER = {
    "reliance": "RELIANCE.NS",
    "tcs": "TCS.NS",
    "tata consultancy": "TCS.NS",
    "hdfc bank": "HDFCBANK.NS",
    "hdfcbank": "HDFCBANK.NS",
    "airtel": "BHARTIARTL.NS",
    "bharti airtel": "BHARTIARTL.NS",
    "icici bank": "ICICIBANK.NS",
    "icicibank": "ICICIBANK.NS",
    "infosys": "INFOSYS.NS",
    "infy": "INFOSYS.NS",
    "sbi": "SBIN.NS",
    "state bank": "SBIN.NS",
    "hindustan unilever": "HINDUNILVR.NS",
    "hul": "HINDUNILVR.NS",
    "itc": "ITC.NS",
    "larsen": "LT.NS",
    "l&t": "LT.NS",
    "kotak": "KOTAKBANK.NS",
    "axis bank": "AXISBANK.NS",
    "bajaj finance": "BAJFINANCE.NS",
    "asian paints": "ASIANPAINT.NS",
    "maruti": "MARUTI.NS",
    "titan": "TITAN.NS",
    "sun pharma": "SUNPHARMA.NS",
    "ultratech": "ULTRACEMCO.NS",
    "nestle": "NESTLEIND.NS",
    "wipro": "WIPRO.NS",
    "ongc": "ONGC.NS",
    "ntpc": "NTPC.NS",
    "power grid": "POWERGRID.NS",
    "mahindra": "M&M.NS",
    "tata motors": "TATAMOTORS.NS",
    "hcl tech": "HCLTECH.NS",
    "hcltech": "HCLTECH.NS",
    "bajaj finserv": "BAJAJFINSV.NS",
    "tata steel": "TATASTEEL.NS",
    "adani enterprises": "ADANIENT.NS",
    "adani ports": "ADANIPORTS.NS",
    "coal india": "COALINDIA.NS",
    "divi": "DIVISLAB.NS",
    "dr reddy": "DRREDDY.NS",
    "eicher": "EICHERMOT.NS",
    "grasim": "GRASIM.NS",
    "hero motocorp": "HEROMOTOCO.NS",
    "hindalco": "HINDALCO.NS",
    "indusind": "INDUSINDBK.NS",
    "jsw steel": "JSWSTEEL.NS",
    "cipla": "CIPLA.NS",
    "bajaj auto": "BAJAJ-AUTO.NS",
    "apollo hospital": "APOLLOHOSP.NS",
    "bpcl": "BPCL.NS",
    "britannia": "BRITANNIA.NS",
    "shriram": "SHRIRAMFIN.NS",
    "sbi life": "SBILIFE.NS",
    "hdfc life": "HDFCLIFE.NS",
    "tech mahindra": "TECHM.NS",
    "tata consumer": "TATACONSUM.NS",
    "ltimindtree": "LTIM.NS",
}
